const actionsType = {
    AUTH_START: "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    PACKAGE_START: "PACKAGE_START",
    GET_PACKAGE_SUCCESS: "GET_PACKAGE_SUCCESS",
    PACKAGE_FAIL: "PACKAGE_FAIL",

    THEME_START: "THEME_START",
    GET_THEME_SUCCESS: "GET_THEME_SUCCESS",
    THEME_FAIL: "THEME_FAIL",
    THEME_CREATE_SUCCESS: "THEME_CREATE_SUCCESS",
    THEME_DELETE_SUCCESS: "THEME_DELETE_SUCCESS",

    KID_START: "KID_START",
    KID_SUCCESS: "KID_SUCCESS",
    KID_FAIL: "KID_FAIL",
}

export default actionsType