const actionsType = {
    AUTH_START: "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    PACKAGE_START: "PACKAGE_START",
    GET_PACKAGE_SUCCESS: "GET_PACKAGE_SUCCESS",
    PACKAGE_FAIL: "PACKAGE_FAIL",

    PACKAGE_ORDER_START: "PACKAGE_ORDER_START",
    PACKAGE_ORDER_SUCCESS: "PACKAGE_ORDER_SUCCESS",
    PACKAGE_ORDER_FAIL: "PACKAGE_ORDER_FAIL",
    GET_PACKAGE_ORDER_SUCCESS: "GET_PACKAGE_ORDER_SUCCESS",

    THEME_START: "THEME_START",
    GET_THEME_SUCCESS: "GET_THEME_SUCCESS",
    THEME_FAIL: "THEME_FAIL",
    THEME_CREATE_SUCCESS: "THEME_CREATE_SUCCESS",
    THEME_DELETE_SUCCESS: "THEME_DELETE_SUCCESS",

    PRODUCT_START: "PRODUCT_START",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    PRODUCT_FAIL: "PRODUCT_FAIL",
    PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
    PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",

    BOX_START: "BOX_START",
    GET_BOX_SUCCESS: "GET_BOX_SUCCESS",
    BOX_CREATE_SUCCESS: "BOX_CREATE_SUCCESS",
    BOX_FAIL: "BOX_FAIL",

    KID_START: "KID_START",
    GET_KID_SUCCESS: "GET_KID_SUCCESS",
    KID_CREATE_SUCCESS: "KID_CREATE_SUCCESS",
    KID_UPDATE_SUCCESS: "KID_UPDATE_SUCCESS",
    KID_FAIL: "KID_FAIL",
}

export default actionsType